
/* Auth */
export const ADD_AUTH_TOKEN = 'ADD_AUTH_TOKEN';
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN';


/* Song Selector */
export const CHANGE_CURRENT_TRACK_METADATA = 'CHANGE_CURRENT_TRACK_METADATA';
export const ADD_CURRENT_TRACK_END_TIME = 'ADD_CURRENT_TRACK_END_TIME'