
/* Auth */
export const ADD_AUTH_TOKEN = 'ADD_AUTH_TOKEN';
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN';


/* Song Selector */
export const CHANGE_CURRENT_TRACK_METADATA = 'CHANGE_CURRENT_TRACK_METADATA';
export const ADD_CURRENT_TRACK_END_TIME = 'ADD_CURRENT_TRACK_END_TIME';

/* Current Album Song List*/
export const CHANGE_ALBUM_LIST_ARTIST_ID = 'CHANGE_ALBUM_LIST_ARTIST_ID';
export const CHANGE_ALBUM_LIST_ALBUM_ID = 'CHANGE_ALBUM_LIST_ALBUM_ID'
export const CHANGE_ALBUM_LIST_ARTIST_NAME = 'CHANGE_ALBUM_LIST_ARTIST_NAME';
export const CHANGE_ALBUM_LIST_ALBUM_NAME = 'CHANGE_ALBUM_LIST_ALBUM_NAME';
export const CHANGE_ALBUM_LIST_TRACK_LIST = 'CHANGE_ALBUM_LIST_TRACK_LIST'